# voer de onderstaande commando's uit om docker compose te runnen
# 1. mvn clean package -Dmaven.test.skip=true
# 2. docker compose build
# 3. docker compose up
# 4. docker compose down --rmi all -v
version: '3'
services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - mysql_userservice
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://rabbitmq:5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  solarparkservice:
    build: SolarParkService
    hostname: solarparkservice
    container_name: solarparkservice
    restart: always
    ports:
      - 8090:8090
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATA_MONGODB_URI: mongodb://mongosolarpark:27017/solarpark

  mongosolarpark:
    hostname: mongosolarpark
    container_name: mongosolarpark
    image: mongo:latest
    volumes:
      - ./database:/datasolarpark
    ports:
      - 27017:27017

  weatherservice:
    build: WeatherService
    hostname: weatherservice
    container_name: weatherservice
    restart: always
    ports:
      - 8110:8110
    environment:
      RABBIT_HOST: rabbitmq
    depends_on:
      - rabbitmq

  userservice:
    build: UserService
    hostname: userservice
    container_name: userservice
    restart: always
    ports:
      - 8130:8130
    environment:
      MYSQL_DB_HOST: mysql_userservice
      RABBIT_HOST: rabbitmq
    depends_on:
      - mysql_userservice

  authenticationservice:
    build: AuthenticationService
    hostname: authenticationservice
    container_name: authenticationservice
    restart: always
    ports:
      - 8100:8100
    environment:
      RABBIT_HOST: rabbitmq
      MYSQL_DB_HOST: mysql_authservice
    depends_on:
      - mysql_authservice

  mysql_authservice:
    container_name: mysql_authservice
    hostname: mysql_authservice
    image: mysql:latest
    ports:
      - 3306:3306
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  mysql_userservice:
    container_name: mysql_userservice
    hostname: mysql_userservice
    image: mysql:latest
    ports:
      - 3307:3306
    restart: always
    expose:
      - 3307
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  gateway_service:
    container_name: gateway
    hostname: gateway
    image: vincentdarwinkel/gateway
    ports:
    - 8081:80
    restart: always

#  regionservice:
#    build: RegionService
#    hostname: regionservice
#    container_name: regionservice
#    restart: always
#    ports:
#      - 8150:8150
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://mongoregion:27018/region

#  mongoregion:
#    hostname: mongoregion
#    container_name: mongoregion
#    image: mongo
#    volumes:
#      - ./database:/mongoregion
#    ports:
#      - 27018:27018

  simulationwindservice:
    build: simulationwindservice
    hostname: simulationwindservice
    container_name: simulationwindservice
    restart: always
    ports:
      - 8140:8140
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATA_MONGODB_URI: mongodb://mongosimulationwindservice:27020/simulation_wind

  mongosimulationwindservice:
    hostname: mongosimulationwindservice
    container_name: mongosimulationwindservice
    image: mongo:latest
    command: mongod --port 27020
    volumes:
      - ./database:/mongosimulationwindservice
    ports:
      - 27019:27019

  energyusageservice:
    build: EnergyUsageService
    hostname: energyusageservice
    container_name: energyusageservice
    restart: always
    ports:
      - 8170:8170
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongoenergyusageservice:27020/energyusage

  mongoenergyusageservice:
    hostname: mongoenergyusageservice
    container_name: mongoenergyusageservice
    image: mongo
    volumes:
      - ./database:/mongoenergyusageservice
    ports:
      - 27020:27017

  energybalanceservice:
    build: EnergyBalanceService
    hostname: energybalanceservice
    container_name: energybalanceservice
    depends_on:
      - rabbitmq
    restart: always
    ports:
    - 8160:8160
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATA_MONGODB_URI: mongodb://mongoenergybalanceservice:27030/energybalance

  mongoenergybalanceservice:
    hostname: mongoenergybalanceservice
    container_name: mongoenergybalanceservice
    command: mongod --port 27030
    image: mongo:latest
    volumes:
      - ./database:/mongoenergybalanceservice
    ports:
      - 27030:27030

  simulationsolarservice:
    build: SimulationSolarService
    hostname: simulationsolarservice
    container_name: simulationsolarservice
    depends_on:
      - rabbitmq
    restart: always
    ports:
      - 8120:8120
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATA_MONGODB_URI: mongodb://mongosolarservice:27040/solar

  mongosolarservice:
    hostname: mongoenergybalanceservice
    container_name: mongoenergybalanceservice
    command: mongod --port 27040
    image: mongo:latest
    volumes:
      - ./database:/mongosolarservice
    ports:
      - 27040:27040
