spring:
  application:
    name: gateway

zuul:
  host:
    # Standard timeout
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    solarpark:
      url: http://localhost:8090/solarpark
    authentication:
      url: http://localhost:8100/auth
    weather:
      url: http://localhost:8110/weather
    simulation:
      url: http://localhost:8120/simulation
    region:
      url: http://localhost:8140/region
server:
  port: 8081
