trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - simulationwindservice/*

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'simulationwindservice/pom.xml'
      goals: 'clean package'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
      checkStyleRunAnalysis: true

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  - task: Docker@2
    inputs:
      containerRegistry: 'energygrideast'
      command: 'login'
      addPipelineData: false

  - task: Docker@2
    inputs:
      containerRegistry: 'energygrideast'
      repository: 'energygrideast/simulationwindservice'
      command: 'buildAndPush'
      Dockerfile: 'simulationwindservice/Dockerfile'
      tags: 'latest'
      addPipelineData: false
  
  - task: Docker@2
    inputs:
      containerRegistry: 'energygrideast'
      command: 'logout'
      addPipelineData: false